# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/bombita/rabe

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/bombita/rabe

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/bombita/rabe/CMakeFiles /home/bombita/rabe/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/bombita/rabe/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named test

# Build rule for target.
test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test
.PHONY : test

# fast build rule for target.
test/fast:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/build
.PHONY : test/fast

src/Algos.o: src/Algos.cpp.o

.PHONY : src/Algos.o

# target to build an object file
src/Algos.cpp.o:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/Algos.cpp.o
.PHONY : src/Algos.cpp.o

src/Algos.i: src/Algos.cpp.i

.PHONY : src/Algos.i

# target to preprocess a source file
src/Algos.cpp.i:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/Algos.cpp.i
.PHONY : src/Algos.cpp.i

src/Algos.s: src/Algos.cpp.s

.PHONY : src/Algos.s

# target to generate assembly for a file
src/Algos.cpp.s:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/Algos.cpp.s
.PHONY : src/Algos.cpp.s

src/BTtree.o: src/BTtree.cpp.o

.PHONY : src/BTtree.o

# target to build an object file
src/BTtree.cpp.o:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/BTtree.cpp.o
.PHONY : src/BTtree.cpp.o

src/BTtree.i: src/BTtree.cpp.i

.PHONY : src/BTtree.i

# target to preprocess a source file
src/BTtree.cpp.i:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/BTtree.cpp.i
.PHONY : src/BTtree.cpp.i

src/BTtree.s: src/BTtree.cpp.s

.PHONY : src/BTtree.s

# target to generate assembly for a file
src/BTtree.cpp.s:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/BTtree.cpp.s
.PHONY : src/BTtree.cpp.s

src/attr_auth.o: src/attr_auth.cpp.o

.PHONY : src/attr_auth.o

# target to build an object file
src/attr_auth.cpp.o:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/attr_auth.cpp.o
.PHONY : src/attr_auth.cpp.o

src/attr_auth.i: src/attr_auth.cpp.i

.PHONY : src/attr_auth.i

# target to preprocess a source file
src/attr_auth.cpp.i:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/attr_auth.cpp.i
.PHONY : src/attr_auth.cpp.i

src/attr_auth.s: src/attr_auth.cpp.s

.PHONY : src/attr_auth.s

# target to generate assembly for a file
src/attr_auth.cpp.s:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/attr_auth.cpp.s
.PHONY : src/attr_auth.cpp.s

src/central_auth.o: src/central_auth.cpp.o

.PHONY : src/central_auth.o

# target to build an object file
src/central_auth.cpp.o:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/central_auth.cpp.o
.PHONY : src/central_auth.cpp.o

src/central_auth.i: src/central_auth.cpp.i

.PHONY : src/central_auth.i

# target to preprocess a source file
src/central_auth.cpp.i:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/central_auth.cpp.i
.PHONY : src/central_auth.cpp.i

src/central_auth.s: src/central_auth.cpp.s

.PHONY : src/central_auth.s

# target to generate assembly for a file
src/central_auth.cpp.s:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/central_auth.cpp.s
.PHONY : src/central_auth.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/myconfig.o: src/myconfig.cpp.o

.PHONY : src/myconfig.o

# target to build an object file
src/myconfig.cpp.o:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/myconfig.cpp.o
.PHONY : src/myconfig.cpp.o

src/myconfig.i: src/myconfig.cpp.i

.PHONY : src/myconfig.i

# target to preprocess a source file
src/myconfig.cpp.i:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/myconfig.cpp.i
.PHONY : src/myconfig.cpp.i

src/myconfig.s: src/myconfig.cpp.s

.PHONY : src/myconfig.s

# target to generate assembly for a file
src/myconfig.cpp.s:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/myconfig.cpp.s
.PHONY : src/myconfig.cpp.s

src/node.o: src/node.cpp.o

.PHONY : src/node.o

# target to build an object file
src/node.cpp.o:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/node.cpp.o
.PHONY : src/node.cpp.o

src/node.i: src/node.cpp.i

.PHONY : src/node.i

# target to preprocess a source file
src/node.cpp.i:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/node.cpp.i
.PHONY : src/node.cpp.i

src/node.s: src/node.cpp.s

.PHONY : src/node.s

# target to generate assembly for a file
src/node.cpp.s:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/node.cpp.s
.PHONY : src/node.cpp.s

src/user.o: src/user.cpp.o

.PHONY : src/user.o

# target to build an object file
src/user.cpp.o:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/user.cpp.o
.PHONY : src/user.cpp.o

src/user.i: src/user.cpp.i

.PHONY : src/user.i

# target to preprocess a source file
src/user.cpp.i:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/user.cpp.i
.PHONY : src/user.cpp.i

src/user.s: src/user.cpp.s

.PHONY : src/user.s

# target to generate assembly for a file
src/user.cpp.s:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/user.cpp.s
.PHONY : src/user.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... test"
	@echo "... src/Algos.o"
	@echo "... src/Algos.i"
	@echo "... src/Algos.s"
	@echo "... src/BTtree.o"
	@echo "... src/BTtree.i"
	@echo "... src/BTtree.s"
	@echo "... src/attr_auth.o"
	@echo "... src/attr_auth.i"
	@echo "... src/attr_auth.s"
	@echo "... src/central_auth.o"
	@echo "... src/central_auth.i"
	@echo "... src/central_auth.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/myconfig.o"
	@echo "... src/myconfig.i"
	@echo "... src/myconfig.s"
	@echo "... src/node.o"
	@echo "... src/node.i"
	@echo "... src/node.s"
	@echo "... src/user.o"
	@echo "... src/user.i"
	@echo "... src/user.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

